StringLoad(s_ErrCap, 'ErrCap');
StringLoad(s_ConfCap, 'ConfCap');
StringLoad(s_SuccCap, 'SuccCap');

StringLoad(s_Ok, 'Ok');
StringLoad(s_Cancel, 'Cancel');

StringLoad(s_Pause, 'Pause');
StringLoad(s_Resume, 'Resume');

StringLoad(s_ErrNoWebcam, 'ErrNoWebcam');
//StringLoad(s_ErrNoOptions, 'ErrNoOptions');
StringLoad(s_ErrStartCap, 'ErrStartCap');
StringLoad(s_ConfRRun, 'ConfRRun');
StringLoad(s_ConfDelete, 'ConfDelete');
StringLoad(s_DeleteOk, 'DeleteOk');
StringLoad(s_ReplFile, 'ReplFile');
StringLoad(s_CopySuccess, 'CopySuccess');
StringLoad(s_CopyError, 'CopyError');

StringLoad(s_InRecord, 'InRecord');
StringLoad(s_RecPause, 'RecPause');
StringLoad(s_InCombine, 'InCombine');
StringLoad(s_InCombineRev, 'InCombineRev');
StringLoad(s_InSetDelay, 'InSetDelay');
StringLoad(s_InSetLoops, 'InSetLoops');
StringLoad(s_Saving, 'Saving');
StringLoad(s_Finishing, 'Finishing');

StringLoad(s_SendImage, 'SendImage');
StringLoad(s_RecipentEnter1, 'RecipentEnter1');
StringLoad(s_RecipentEnter2, 'RecipentEnter2');
StringLoad(s_SelImgSendDest, 'SelImgSendDest');

StringLoad(s_Ready, 'Ready');
StringLoad(s_Recording, 'Recording');
StringLoad(s_Paused, 'Paused');
StringLoad(s_AnimSaved, 'AnimSaved');

StringLoad(s_CameraName, 'CameraName');

StringLoad(s_SendMailHint, 'SendMailHint');
StringLoad(s_WebsiteHint, 'WebsiteHint');
